spring:
  application:
    name: eureka-client-admin-service
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.wizpower.eurekaclient.bean
server:
  port: 9000
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud-ida?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

